### ISSUE TITLE
dealing columns in task.load_data_frame

### ISSUE THREAD

**Issue by mpozpnd** [m3dev/gokart#104]
If param required_columns is None and input is an empty df,  task.load_data_frame() returns an empty df with **no** columns. In some cases, a KeyError may occur in the next task. 
So in this case, it should set the original columns as they are.

**Comment by mski-iksm** [comment]
@mpozpnd 
Thank you for noticing the issue.

This issue is now solved at following PR.
https://github.com/m3dev/gokart/pull/137/files#diff-e4f17284fbc6c32f4f5319fb017d9485b0a1cd7c95e9eef78af8c7323382749cR200
May I close this issue?
