### ISSUE TITLE
Redundant warning messages about redis_host, redis_port.

### ISSUE THREAD

**Issue by skokado** [m3dev/gokart#166]
Hi, thank you for this project.

I faced displaying warning messages when running tasks after updating `gokart` recently.

- gokart==0.3.23
- luigi==3.0.2

`tasks.py` (almost do nothing task)

```python
import gokart
import pandas as pd


class MyTask(gokart.TaskOnKart):
    def output(self):
        return self.make_target('output.csv')

    def run(self):
        df = pd.DataFrame()
        self.dump(df)
```

```shell
$ python3 -m luigi --local-scheduler --module tasks MyTask --log-level=INFO
.../site-packages/luigi/parameter.py:279: UserWarning: Parameter "redis_host" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
.../site-packages/luigi/parameter.py:279: UserWarning: Parameter "redis_port" with value "None" is not of type string.
  warnings.warn('Parameter "{}" with value "{}" is not of type string.'.format(param_name, param_value))
INFO: Informed scheduler that task   MyTask__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
...
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====
```

This is caused by using `luigi.Paremeter` class for `redis_host` and`redis_port`, and default value is `None`.

I think, it is better to use `luigi.OptionalParamter` when default value is `None` instead of `luigi.Parameter`.

In the implementation of the displaying warning, `luigi.OptionalParamter` has a check for the value being None, but `luigi.Paramter` does not.

- `luigi.OptionalParamter._warn_on_wrong_param_type`

https://github.com/spotify/luigi/blob/7b7ff901480d9a02402037e0cb54e4508b5a94a2/luigi/parameter.py#L338-L343

- `luigi.Paramter._warn_on_wrong_param_type`

https://github.com/spotify/luigi/blob/7b7ff901480d9a02402037e0cb54e4508b5a94a2/luigi/parameter.py#L275-L279

**Comment by skokado** [comment]
I have confirmed that the warning doesn't display by using `OptionalParameter` as below.

```python
import luigi
import gokart
import pandas as pd


class BaseTaskOnKart(gokart.TaskOnKart):
    # override
    redis_host = luigi.OptionalParameter(default=None, description='Task lock check is deactivated, when None.', significant=False)
    redis_port = luigi.OptionalParameter(default=None, description='Task lock check is deactivated, when None.', significant=False)


class MyTask(BaseTaskOnKart):

    def output(self):
        return self.make_target('output.csv')

    def run(self):
        df = pd.DataFrame()
        self.dump(df)

```

**Comment by mski-iksm** [comment]
@skokado 
Thank you for your suggestion.

We will fix this issue in the next release!
