### ISSUE TITLE
Feature request: Set logging level for gokart.build

### ISSUE THREAD

**Issue by TaylerUva** [m3dev/gokart#211]
Allow setting of logging level in gokart.build. I would like to be able to see info logs I've created in my tasks without having to see gokart debug messages. This is useful for Juptyer Notebooks.

https://github.com/m3dev/gokart/blob/575207f5d348b8c1afbb6d1af3777c67230e15ed/gokart/build.py#L41-L51

**Comment by vaaaaanquish** [comment]
@TaylerUva [ASK]
There is a way to make a config, what do you think of it?
example: https://gist.github.com/vaaaaanquish/8719a3470aa83c7985c5416ece0299c0

Or do you think `gokart.build` argument would be better?

**Comment by TaylerUva** [comment]
For my use case a config would be better. As long as that will work with logging from other classes.

i.e. `I'm a log!` will get logged when `do_thing()` is called in `TaskOnKart.run`
```python
from logging import getLogger


class MyClass:
    logger = getLogger(__name__)
    def do_thing():
        self.logger.info("I'm a log!")
```

Doing it through a config will also make your existing documentation more true. (I had to look at source code to realize the logging config was ignored by build)

**Comment by vaaaaanquish** [comment]
> Doing it through a config will also make your existing documentation more true. (I had to look at source code to realize the logging config was ignored by build)

That's right. I think so too, that's very confusing.

**Comment by vaaaaanquish** [comment]
I was reading luigi. It looks like putting the logger configuration to `luigi.build` args.
