### ISSUE TITLE
Question: how to save folder based data?

### ISSUE THREAD

**Issue by miyamonz** [m3dev/gokart#238]
Models in [huggingface/transformers](https://huggingface.co/transformers/index.html) have save_pretrianed and from_pretrained methods.
these methods save and load config.json and pytorch_model.bin in specified dir path.

```python
model.save_pretrained('./dirname') # ./dirname directory created.
SomeModel.from_pretrained('./direname')
```
I want to dump and load such a directory as target. Is there a way to do this?

**Comment by hirosassa** [comment]
@miyamonz Thank you for writing in! Cloud we close this issue?
