### ISSUE TITLE
[Bug] NameError is raised when execute gokart.run() with _try_tree_info() in IPython

### ISSUE THREAD

**Issue by yuta100101** [m3dev/gokart#247]
Running the following code will raise NameError in IPython.

```py
import gokart

class Task(gokart.TaskOnKart):
	pass

gokart.run(["Task", "--tree-info-mode=simple"])
```
```
NameError: name 'exit' is not defined
```

And the same is true when execute `gokart.run(["Task", "--delete-unnecessary-output-files"])`.

This might be resolved by replacing `exit()` with `sys.exit()` in `_try_tree_info()` and `_try_to_delete_unnecessary_output_file()`.

**Comment by Hi-king** [comment]
@yuta100101 

We believe #248 have fixed this :) 

And we've released hotfix version 1.0.4. Really thx for your contribution!
