### ISSUE TITLE
fail_on_empty_dump cannot be executed as in the example in the document

### ISSUE THREAD

**Issue by yamasakih** [m3dev/gokart#281]
Hi,

Thank you for your documentation. The documentation describing useful methods for Pandas is very helpful.
But, when I tried to execute `fail_on_empty_dump` as described in the documentation, I got the following error.

```python
def run(self):
    ...
    self.fail_on_empty_dump(df)
```

cf. https://gokart.readthedocs.io/en/latest/for_pandas.html#fail-on-empty-dataframe

```python
Traceback (most recent call last):
  File "/opt/conda/envs/sample/lib/python3.6/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/opt/conda/envs/sample/lib/python3.6/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/workspaces/sample/task.py", line 475, in run
    self.fail_on_empty_dump(df)
TypeError: 'bool' object is not callable
```

I think this error occurred because `fail_on_empty_dump` is a parameter, i.e. attribute, and not a method.

https://github.com/m3dev/gokart/blob/27358e28bcada98027bd4541f5e6f161192fb49e/gokart/task.py#L64

I have submitted a pull request with updated documentation to describe it as a parameter, so please merge it if you like.
https://github.com/m3dev/gokart/pull/282

**Comment by Hi-king** [comment]
#282 has merged. Thx.
