### ISSUE TITLE
[Suggestion] use ruff instead of flake8

### ISSUE THREAD

**Issue by kitagry** [m3dev/gokart#344]
Hi everyone. I have a suggestion like title.

We use `pyproject-flake8` in order to aggregate setting to `pyproject.toml`. Currently, `flake8` doesn't support `pyproject.toml` and `pyproject-flake8`'s deployment is delayed. So, I think it is better to use ruff, because it support `pyproject.toml` (and it is very fast!).

Do you think this suggestion?

**Comment by hirosassa** [comment]
Sounds good! I agree with your opinion
