### ISSUE TITLE
bug: mypy plugin doesn't collect all gokart.TaskOnKart attributes

### ISSUE THREAD

**Issue by kitagry** [m3dev/gokart#388]
I used mypy plugin, but some parameters are warned by mypy.

```python
task = _Task(redis_port=1111) # OK
task = _Task(complete_check_at_run=False)  # Unexpected keyword argument "complete_check_at_run"
```

It seems [`info.metadata`](https://github.com/m3dev/gokart/blob/222c40ac4cb0f183a4c287ea19f4584ae7350a0c/gokart/mypy.py#L263) is restricted to some length.

**Comment by hiro-o918** [comment]
I found this PR fixes this issue when `py.typed` is located under luigi.
https://github.com/m3dev/gokart/pull/389
