### ISSUE TITLE
add file load generator

### ISSUE THREAD

**Issue by 6syun9** [m3dev/gokart#47]
Hi.

I want the following `load_generator` features.
```
class Hoge(gokart.TaskOnKart):
    
    ...

    def run(self):
        for x in self.load_generator('piyo'):
            proccess_file(x)
```
`gorkart` is the pipeline for data processing. I think `load_generator` is effective for sequential processing and large file that couldn't ride on memory. How do you think?
Thanks.

**Comment by nishiba** [comment]
Hi. 
Thank you for your proposal. I agree with you.
Would you implement the function?
