### ISSUE TITLE
can't loaded parameter with correct type from config file

### ISSUE THREAD

**Issue by 6syun9** [m3dev/gokart#49]
Hi.
I want load parameter from config file.
But, we can't loaded parameter with correct type from config file.

Example script:
```
# hoge.py
import luigi
import gokart

class Hoge(gokart.TaskOnKart):
    sample_param = luigi.FloatParameter()
    
    ...

    def run(self):
        print(type(self.sample_param))

if __name__ == '__main__':
    luigi.configuration.LuigiConfigParser.add_config_path('sample.ini')
    luigi.run(main_task_cls=Hoge)
```
```
# sample.ini
[Hoge]
sample_param=0.1
```
　　
param from cli (This is correct behavior):
```
$ python hoge.py --sample-param=0.1 --local-scheduler
<class 'float'>
```

param from sample.ini:
```
$ python hoge.py --local-scheduler
<class 'str'>
```

In luigi, It will be parsed even from config.
This issue also happens outside of FloatParameter.
Parameter modules: https://luigi.readthedocs.io/en/stable/api/luigi.parameter.html

**Comment by nishiba** [comment]
I think that __init__ of TaskOnGokart causes this problem. I will try to fix it. Thanks.

**Comment by 6syun9** [comment]
Sorry. 
This problem solve by using `gokart.run()` .

I hit this problem trying to unify parameters in multiple tasks.
Maybe, I solve by using `inherits` and `requires` . I will try it.
