### ISSUE TITLE
dump module version

### ISSUE THREAD

**Issue by vaaaaanquish** [m3dev/gokart#83]
We need to save the module version for reproducibility.

Some say it can be kept in `pipenv`, `requirements.txt` and more.
But It's hard to require all gokart modules.

solution:
- request `Pipfile.lock` for all gokart user
- `pip freeze > lib_ver.log`
- lookup `hoge.__version__`

**Comment by 6syun9** [comment]
- lookup `hoge.__version__` example
```
import sys
from importlib import import_module

for x in set([x.split('.')[0] for x in sys.modules.keys() if '_' not in x]):
    module = import_module(x)
    if '__version__' in dir(module):
        module_versions.append(f'{x}=={module.__version__.split(" ")[0]}')
```
